config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  get 'history', to: 'comments#history'

  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number
  has_rich_text :body

  # Polymorphic Comments
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def set_comment_number
    self.comment_number = user.comment_created
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  # Active Storage from Rails 5
  has_one_attached :thumbnail
  has_one_attached :banner
  # Action Text from Rails 6
  has_rich_text :body

  validates :title, length: { minimum: 5 }
  validates :body,  length: { minimum: 25 }

  self.per_page = 10
  extend FriendlyId

  friendly_id :slug_candidates, use: :slugged

  def optimized_image(image,x,y)
    image.variant(resize_to_fill: [x, y]).processed if image.present?
  end

  def slug_candidates
    [
      title,
      [title, id],
      "post-#{SecureRandom.hex(4)}"
    ]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validate :validate_username

  attr_writer :login

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def comment_created
    # This is the same thing as num_comments += 1
    self.number_of_comments = number_of_comments + 1
    save
    number_of_comments
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :is_admin!

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def is_admin!
    if current_user&.admin
    else
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create]
  before_action :set_comment, except: [:create]
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.reply = true if params[:comment_id]
    @comment.save
  end

  def edit; end

  def update
    if @comment.edit_history == ''
      # if \n => replace \n with <br/><hr/>
      @comment.edit_history = 'Original: ' + @comment.body.body.to_plain_text + "\n"
    else
      @comment.edit_history = @comment.edit_history + 'Edit: ' + params[:comment][:body] + "\n"
    end
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  def history; end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    # Comment
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:post_id]
      @commentable = Post.friendly.find(params[:post_id])
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :is_admin!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
    @comments = @post.comments.order('created_at DESC')

    @num_comments = @post.comments.count
    @post.comments.each do |comment|
      @num_comments += comment.comments.count
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :thumbnail, :banner)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper

end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="comment-container" id="comment-<%= comment.id %>">
    <div class="container">
        <%= render 'comments/comments', comment: comment, local: Comment.new %>


        <% unless comment.reply %>
        <div class="row">
            <div class="col-4">
            </div>
            <div class="col-8">
                <div class="comment-form-nested">
                    <%= render 'comments/form', commentable: comment, local: Comment.new %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
    <div class="col-3">
        <div class="row">
            <% if comment.user.avatar.attached? %>
            <%= image_tag(comment.user.avatar, class:'comment-avatar') %>
            <% else %>
            <%= image_tag("/default_profile.png", class:'comment-avatar') %>
            <% end %>
        </div>
        <div class="row">
            <div class="comment-timestamp" id="edit-history-text-<%= comment.id%>">
                <%= render 'comments/edit_history_text', comment: comment%>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="row">
            <div class="col-8">
                <div class="comment-username">
                    <%= comment.user.username%>
                </div>
                <div class="comment-number">
                    #<%= comment.comment_number%>
                </div>
            </div>

            <% if current_user && (current_user == comment.user || current_user.admin)%>
            <div class="col-4 text-right" style="padding-right: 0;">
                <div class="button-group" role="group" aria-label="Edit and Delete Button Group">
                    <%= link_to "Edit", edit_comment_path(comment), class: 'btn btn-warning', remote: true %>
                    <%= link_to "Delete", comment, class:'btn btn-danger', method: :delete, remote: true %>
                </div>
            </div>
            <% end %>
        </div>
        <hr class="md-4">
        <div class="comment-body" id="comment-body-<%= comment.id %>">
            <%= comment.body %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-3"></div>
    <div class="col-9">
        <div class="inner-comment-container" id="reply-<%=comment.id%>">
            <% comment.comments.each do |comment|%>
            <%= render comment %>
            <% end %>
        </div>
    </div>
</div>

<!-- Modal-->
<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelledby="Comment Edit History" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <h5 class="modal-title" id="edit_history_title">Edit History</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="edit-history-body">
                <%= render 'comments/edit_history', comment: comment %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history.gsub(/\n/, '<br/><hr/>').html_safe %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br />
<% edit_history = comment.edit_history == "" ? "" : "Last edited " + time_ago_in_words(comment.updated_at) + " ago" %>
<%= link_to(edit_history, 'javascript:;', data: {toggle: "modal", target: "#edit_history"})%>

app/views/comments/_form.html.erb
<% if current_user %>
<div class="row">
    <div class="comment-form">
        <%= form_with model: [commentable, local] do |f| %>
        <div class="form-group">
            <%= f.rich_text_area :body, placeholder: "Say something...", class:"reply-form-#{commentable.id}", id: f.object.object_id, method: :patch %>
            <%= f.submit "Post", class:'btn btn-dark float-right' %>
        </div>
        <% end %>
    </div>
</div>

<script>
    $(document).on("turbolinks:load", function() {
        $(".trix-button-group--file-tools").remove();
        document.addEventListener("trix-file-accept", function(event) {
            event.preventDefault();
        });
    });
</script>

<% else %>
<div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
        <h2 class="comment-login-prompt"><%= link_to "Login", new_user_session_path %> to comment</h2>
    </div>
    <div class="col-2"></div>
</div>
<% end %>

app/views/comments/create.js.erb
if ("<%= @comment.reply %>" === 'true') {
    var comment_pane;

    if ("<%= @commentable.comments.count %>" === "0") {
        comment_pane = "#reply-container-<%=@commentable.id %>";
    } else {
        comment_pane = "#reply-<%=@comment.commentable_id %>";
    }

    $(comment_pane).append("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
} else {
    $("#comment-pane").prepend("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
}
$('.trix-button-group--file-tools').remove();

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= j render 'comments/form', commentable: @comment.commentable, local: @comment %>");
$(".trix-button-group--file-tools").remove();

app/views/comments/update.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= raw @comment.body.body.to_html() %>");

$("#edit-history-body").html("<%= j render 'comments/edit_history', comment: @comment %>");

$("#edit-history-text-<%= @comment.id %>").html("<%= j render 'comments/edit_history_text', comment: @comment %>");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="<%= root_path %>">Home</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <% if current_user %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.username %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <% if current_user.admin %>
                    <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
                    <% end %>
                    <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Logout", destroy_user_session_path, class:'dropdown-item', method: :delete %>
                </div>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogEpisode1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  
  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
    <%= f.label :thumbnail, class:'form-control' %>
    <%= f.file_field :thumbnail %>
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="digg_pagination">
            <%= will_paginate(@posts, :container => false) %>
        </div>
    </div>
    <%= link_to "New Post", new_post_path %>

    <% @posts.each do |post| %>
    <div class="row">
        <div class="card mb-3">
            <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card" />
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to post.title, post %>
                </h5>
                <p class="card-text">
                    <%= post.body.to_plain_text.truncate_words(50) %>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
                        <%= post.user.username %> | <%= pluralize(post.views, "View") %> |
                        <% @num_comments = post.comments.count %>
                        <% post.comments.each do |comment| %>
                        <% @num_comments += comment.comments.count %>
                        <% end %>

                        <%= pluralize(@num_comments, "Comment") %> |
                        <% if current_user && (current_user.admin || current_user == post.user)%>
                        <%= link_to "Delete", post, method: :delete %>
                        <% end %>
                    </small>
                </p>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
    <%= image_tag(@post.banner, style:'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
    <div class="row">
        <div class="jumbotron" style="width:100%">
            <h1 class="display-4">
                <%= link_to @post.title, root_path %>
            </h1>
            <p class="lead">
                <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %> |
                <%= pluralize(@num_comments, "Comment") %> |
                <% if current_user && (current_user.admin || current_user == @post.user)%>
                <%= link_to "Delete", @post, method: :delete %>
                <% end %>
            </p>
            <hr class="my-4" />
            <div class="post_body">
                <%= @post.body %>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <%= render 'comments/form', commentable: @post, local: Comment.new %>

    <div id="comment-pane">
        <% @comments.each do |comment| %>
        <%= render comment %>
        <% end %>
    </div>
</div>